### ISSUE TITLE
Allow loading of already instantiated EntityDefinitionProviders

### ISSUE THREAD

**Issue by abenerd** [ergebnis/factory-bot#503]
When using `factory-bot` in a framework one might want to use additional dependencies in their `DefinitionProvider`s, allowing already instantiated providers to be loaded allows the framework to inject the required dependencies before passing the provider to the `FixtureFactory`.

**Comment by localheinz** [comment]
@abenerd 

I'll work on this next, definitely needs this in a few projects.
