### ISSUE TITLE
Possibility to create variants of the same entity?

### ISSUE THREAD

**Issue by mtancoigne** [ergebnis/factory-bot#797]
Hello!

Is there is a way to create factory variants ?

As an example, I have some `Post` with several possible states, based on multiple field values (ex: `published_by_id` + `published_at` = `published` state). 

As I see how `define` works now, maybe the easiest way would be to add a `name` parameter (`define($className, $fieldDefinitions, $afterCreate, $name)` so we can use it like

```php
// Factory
// -----------------------
$baseFields = [
   // ... common fields
];

$fixtureFactory->define(Entity\Post::class, $baseFields);

$fixtureFactory->define(Entity\Post::class, array_merge($baseFields, [
   // Overrides and/or new fields
], null, 'published'));

// In tests
// -----------------------
$this->fixtureFactory()->createOne(Post, 'published');
```

What do you think ?

**Comment by mvhirsch** [comment]
Looks like it's related to #506. Sadly no solution by now.
